### ISSUE TITLE
contrasts file

### ISSUE THREAD

**Issue by DoaneAS** [ZuberLab/crispr-mageck-nf#1]
Hi,  thanks for putting this together.  

I'm trying to understand the contrasts.txt file and how to indicate my design matrix for the analysis.  How does one specify baseline (time 0), for the treatment and control conditions?  Also, why do some entries in the table take a list of multiple samples?

Why not stick with the [design matrix format](https://sourceforge.net/p/mageck/wiki/input/#design-matrix-file) that mageck normally takes as input?

**Comment by jeslipp** [comment]
Hi & thanks for your feedback. The pipeline currently uses RRA (mageck test) not MLE (mageck mle) for calculating the gene-level statistics. My guess is that you are trying to run MLE?

The reasoning for using a contrast file is that you can run many comparisons in parallel and add new ones by just amending the contrast file. A design matrix is limited to a single fixed comparison. You would need as many design matrices as comparisons.
